#!/usr/bin/env bash

#
# Help dialog definition
#
helpDialog="
\033[32m  _                _                     _
 | |              | |                   | |
 | |__   __ _  ___| | ___ __   ___  _ __| |_
 | '_ \ / _\` |/ __| |/ / '_ \ / _ \| '__| __|
 | |_) | (_| | (__|   <| |_) | (_) | |  | |_
 |_.__/_\__,_|\___|_|\_\ .__/ \___/|_|   \__|
      | |              | |
   ___| |__   ___ _ __ |_|_ _   _
  / __| '_ \ / _ \ '__| '__| | | |
 | (__| | | |  __/ |  | |  | |_| |
  \___|_| |_|\___|_|  |_|   \__, |
                             __/ |
                            |___/\033[0m

\033[3mA script to cherry-pick a commit and apply it to several branches based on tags.\033[0m

---------------------------------------------------------------------------------

\033[4mUsage\033[0m:
$(basename "$0") [-h|--help] [-c|--commit abcd1234] [-t|--tags \"v1.0.0 v1.0.1 \"] [-p|--prefix backport] [-s|--suffix fixed-an-issue] [-r|--remote origin] [-rb|--release-branch] [-pr|--pull-request] [-v|--verbose]

\033[4mArguments:\033[0m
    -h|--help              \033[3mDisplay this help dialog.\033[0m
    -c|--commit            \033[3mThe SHA of the commit to cherry-pick.\033[0m
    -t|--tags              \033[3mA list of tags to apply the cherry-picked commit to.\033[0m
    -s|--suffix            \033[3mThe suffix to use for the branches\033[0m
    -p|--prefix            \033[3mThe prefix to use for the branches (defaults to 'backport')\033[0m
    -r|--remote            \033[3mThe remote to push the branches to (defaults to 'origin')\033[0m
    -rb|--release-branch   \033[3mCreates release branches if provided (Naming scheme 'release/[TAG]')\033[0m
    -pr|--pull-request     \033[3mAutomatically create a PR to the release branch on Github\033[0m
                           \033[3mRequires the 'hub' command. More information: https://github.com/github/hub\033[0m
    -v|--verbose           \033[3mOutput additional information during execution\033[0m"

#
# Param verification
#
declare -a tags
declare -a prUrlCollection

while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -c|--commit)
    commit="$2"
    shift # past argument
    shift # past value
    ;;
    -t|--tags)
    IFS=' ' read -r -a tags <<< "$2"
    shift # past argument
    shift # past value
    ;;
    -p|--prefix)
    prefix="$2"
    shift # past argument
    shift # past value
    ;;
    -s|--suffix)
    suffix="$2"
    shift # past argument
    shift # past value
    ;;
    -rb|--release-branch)
    createReleaseBranch=1
    shift # past argument
    ;;
    -pr|--pull-request)
    if [ "$createReleaseBranch" -ne 1 ]; then
      echo "Pull request cannot be created if release branches are not automatically generated.
Please provide the '-rb' option, or run '$(basename "$0") --help' for more information.";
    fi
    command -v hub >/dev/null 2>&1 || {
      echo "It looks like the \"hub\" command is not available. We use this to automatically create PR's
Please install the \"hub\" command. For more information, please visit: https://github.com/github/hub";
      exit 1;
    }
    createPR=1
    shift # past argument
    ;;
    -v|--verbose)
    verbose=1
    shift # past argument
    ;;
    -h|--help)
    echo -e "$helpDialog"
    exit;
    ;;
    *)    # unknown option
    echo "$1" is not a valid argument
    echo ""
    echo -e "$helpDialog"
    exit;
    ;;
esac
done

#
# Manual argument input
#
if [ "$commit" == "" ]; then
  read -rp 'Commit to cherry-pick:' commit
  if [ "$commit" == "" ]; then
    echo A commit SHA is required.
    exit;
  fi
fi

if [ ${#tags[@]} -eq 0 ]; then
  echo 'Which tags would you like to update:'
  read -a tags
  if [ ${#tags[@]} -eq 0 ]; then
    echo At least 1 tag should be provided
    exit;
  fi
fi

if [ "$prefix" == "" ]; then
  read -rp 'Branch prefix [backport]:' prefix
  if [ "$prefix" == "" ]; then
    echo "Using default value \"backport\""
    prefix="backport"
  fi
fi

if [ "$suffix" == "" ]; then
  read -rp 'Branch suffix:' suffix
fi

if [ "$suffix" != "" ]; then
    suffix="/$suffix"
fi

if [ "$remote" == "" ]; then
  read -rp 'Git remote [origin]:' remote
  if [ "$remote" == "" ]; then
    echo "Using default value \"origin\""
    remote="origin"
  fi
fi

echo ""

#
# Script logic
#
for tag in "${tags[@]}"
do
  if [ "$verbose" -eq 1 ]; then
    echo Cherry-picking commit "$commit" for tag "$tag"
  fi

  branchName="$prefix/$tag$suffix"

  if [ "$verbose" -eq 1 ]; then
    echo Creating branch "$branchName"
  fi

  if ! git checkout -b "$branchName" "$tag" &> /dev/null;
  then
      echo "Git failed to checkout branch \"$branchName\"."
      echo "Command that failed was \"git checkout -b $branchName $tag\""
      exit 1;
  fi

  if [ "$verbose" -eq 1 ]; then
    echo Cherry picking commit "$commit"
  fi

  if ! git cherry-pick -x "$commit" &> /dev/null;
  then
      echo "Unable to cherry-pick commit \"$commit\"."
      echo "Command that failed was \"git cherry-pick -x $commit\""
      exit 1;
  fi

  if [ "$verbose" -eq 1 ]; then
    echo Pushing branch to remote "$remote"
  fi

  if ! git push -u "$remote" "$branchName" &> /dev/null;
  then
      echo "Unable to push \"$branchName\" to \"$remote\"."
      echo "Command that failed was \"git push -u $remote $branchName\""
      exit 1;
  fi

  #
  # Release branch creation
  #
  if [ "$createReleaseBranch" -eq 1 ]; then
    releaseBranchName="release/${tag//v}";

    if [ "$verbose" -eq 1 ]; then
      echo Creating release branch "$releaseBranchName"
    fi

    if ! git checkout -b "$releaseBranchName" "$tag" &> /dev/null;
    then
      echo "Git failed to checkout branch \"$releaseBranchName\"."
      exit 1;
    fi

    if [ "$verbose" -eq 1 ]; then
      echo Pushing release branch to remote "$remote"
    fi

    if ! git push -u "$remote" "$releaseBranchName" &> /dev/null;
    then
        echo "Unable to push \"$releaseBranchName\" to \"$remote\"."
        exit 1;
    fi

    #
    # PR Creation
    #
    if [ "$createPR" -eq 1 ]; then
      if [ "$verbose" -eq 1 ]; then
        echo Creating PR from branch "$branchName" '>' "$releaseBranchName"
      fi
      prUrl=$(hub pull-request --no-edit --base "$releaseBranchName" --head "$branchName");
      prUrlCollection+=("$prUrl")
    fi
  fi

  echo "Cherry-picked \"$commit\" into new branch \"$branchName\", and pushed to \"$remote\"

--------------------------------------------------------------------------------------------
";
done

if [ "$createPR" -eq 1 ]; then
  echo "You've chosen to create PR's. Here are the links to the created pull-requests"
  for url in "${prUrlCollection[@]}"
  do
     echo "$url"
  done
fi

echo Finished picking cherries!;
